---
# roles/ansible_role_beszel_agent/handlers/main.yml

- name: Restart beszel-agent
  community.docker.docker_compose_v2:
    project_src: "{{ beszel_agent_dir }}"
    state: present
    recreate: always
